title: Resume | Minseon Park
author: Minseon Park
email: minseonpark00@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  A software developer/Major Computer Science in SFSU 
  샌프란시스코주립대학에서 컴퓨터공학을 전공하고 개발을 하고 있습니다.
show_excerpts: true # set to true to show excerpts on the homepage
remote_theme: thelehhman/texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Minseon Park
  tagline: Developer 
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
#     twitter: thelehhman
    github:  "https://github.com/minseon-park"
#     linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: texture


plugins:
  - jekyll-seo-tag
#  - jekyll-feed
